export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('vegetables').del()

  // Inserts seed entries
  await knex('vegetables').insert([
    {
      id: 1,
      name: 'Potatoes',
      scientific_name: 'Solanum tuberosum',
      description: 'Tuberous crop grown underground; staple in many gardens.',
      soil_id: 1,
      spacing_id: 1,
      requirements_id: 1,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cool (10–15°C), dark, 2–4 months',
      image: '/potatoes.webp',
      image2: '/soil1.webp',
      image3: '/potatohar.webp',
      image4: '/potatostore.webp',
      consumption_adult_kg: 61,
      consumption_child_kg: 37,
    },
    {
      id: 2,
      name: 'Onions',
      scientific_name: 'Allium cepa',
      description:
        'Bulb vegetable, grown from sets or seeds; good for long-term storage.',
      soil_id: 5,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage: 'Dry, ventilated, months',
      image: '/onion.webp',
      image2: '/soil5.webp',
      image3: '/onionhar.webp',
      image4: '/onionjam.webp',
      consumption_adult_kg: 9,
      consumption_child_kg: 5,
    },
    {
      id: 3,
      name: 'Pumpkin',
      scientific_name: 'Cucurbita maxima',
      description:
        'Large vining plant producing sweet, nutritious fruit that stores well through winter.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 100,
      days_to_harvest_max: 140,
      yield_per_plant_min: 2,
      yield_per_plant_max: 5,
      storage:
        'Cure for 7–10 days, then store in a cool, dry place for 3–6 months.',
      image: '/pumpkin.webp',
      image2: '/soil3.webp',
      image3: '/pumpkinhar.webp',
      image4: '/pumpkinstorage.webp',
      consumption_adult_kg: 7,
      consumption_child_kg: 4,
    },
    {
      id: 4,
      name: 'Broccoli',
      scientific_name: 'Brassica oleracea var. italica',
      description: 'Edible flowering heads rich in nutrition.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Refrigerate 1–2°C, up to a week',
      image: '/broccoli2.webp',
      image2: '/soil4.webp',
      image3: '/broccolihar.webp',
      image4: '/broccolisto.webp',
      consumption_adult_kg: 7.5,
      consumption_child_kg: 4.5,
    },
    {
      id: 5,
      name: 'Cauliflower',
      scientific_name: 'Brassica oleracea var. botrytis',
      description: 'Compact white heads; needs consistent growth.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.4,
      yield_per_plant_max: 1.0,
      storage: 'Refrigerate 1–2°C, use within a week',
      image: '/cauliflower.webp',
      image2: '/soil4.webp',
      image3: '/cauliflowerhar.webp',
      image4: '/caulistorage.webp',
      consumption_adult_kg: 5.5,
      consumption_child_kg: 3.3,
    },
    {
      id: 6,
      name: 'Cabbage',
      scientific_name: 'Brassica oleracea var. capitata',
      description: 'Dense leafy head vegetable.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1.5,
      storage: 'Cool 0–2°C, several weeks',
      image: '/cabbage.webp',
      image2: '/soil4.webp',
      image3: '/cabbagehar.webp',
      image4: '/cabkimchi.webp',
      consumption_adult_kg: 6,
      consumption_child_kg: 4,
    },
    {
      id: 7,
      name: 'Lettuce',
      scientific_name: 'Lactuca sativa',
      description: 'Leafy salad green, prefers cool moist conditions.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Refrigerate 0–2°C, 5–7 days',
      image: '/lettuce2.webp',
      image2: '/soil5.webp',
      image3: '/lettuce.webp',
      image4: '/lettucesto.webp',
      consumption_adult_kg: 5,
      consumption_child_kg: 3,
    },
    {
      id: 8,
      name: 'Spinach',
      scientific_name: 'Spinacia oleracea',
      description: 'Leafy green, fast-growing in cool seasons.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 30,
      days_to_harvest_max: 50,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Refrigerate 0–2°C, use within days',
      image: '/spinach.webp',
      image2: '/soil5.webp',
      image3: '/spinachhar.webp',
      image4: '/spinachsto.webp',
      consumption_adult_kg: 5,
      consumption_child_kg: 3,
    },
    {
      id: 9,
      name: 'Silverbeet',
      scientific_name: 'Beta vulgaris subsp. cicla',
      description: 'Productive leafy green with colourful stems.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate 0–2°C, ~5–7 days',
      image: '/silverbeet.webp',
      image2: '/soil5.webp',
      image3: '/silverbeethar.webp',
      image4: '/silverbeetchip.webp',
      consumption_adult_kg: 4,
      consumption_child_kg: 2.5,
    },
    {
      id: 10,
      name: 'Kale',
      scientific_name: 'Brassica oleracea var. sabellica',
      description: 'Hardy leafy green; tolerates frost.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate, use within 7–10 days',
      image: '/kale.webp',
      image2: '/soil4.webp',
      image3: '/kalehar.webp',
      image4: '/kalechip.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 2,
    },
    {
      id: 11,
      name: 'Garden Peas',
      scientific_name: 'Pisum sativum var. sativum',
      description:
        'Cool-season climbing or bush pea grown for its sweet shelled peas.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 60,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.6,
      storage:
        'Refrigerate fresh peas for 3–5 days or freeze soon after harvesting.',
      image: '/peas.webp',
      image2: '/peatrelis.webp',
      image3: '/peahar.webp',
      image4: '/peapickle.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 1.8,
    },
    {
      id: 12,
      name: 'Green Beans',
      scientific_name: 'Phaseolus vulgaris',
      description:
        'Tender annual producing crisp green pods. Bush and climbing varieties are both productive through summer.',

      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 65,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate for up to one week or blanch and freeze.',
      image: '/green-beans.webp',
      image2: '/greenbean-trellis.webp',
      image3: '/greenbeeanhar.webp',
      image4: '/greenbeanjar.webp',
      consumption_adult_kg: 4,
      consumption_child_kg: 2.4,
    },
    {
      id: 13,
      name: 'Carrots',
      scientific_name: 'Daucus carota',
      description: 'Root vegetable, prefers deep loose soil.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Cool, dark, ventilated, 2–3 months',
      image: '/carrots.webp',
      image2: '/soil3.webp',
      image3: '/carrothar.webp',
      image4: '/carrotcake.webp',
      consumption_adult_kg: 18,
      consumption_child_kg: 11,
    },
    {
      id: 14,
      name: 'Beetroot',
      scientific_name: 'Beta vulgaris',
      description: 'Root vegetable; leaves edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.4,
      storage: 'Cool dark, 2–3 months',
      image: '/beetroot.webp',
      image2: '/soil3.webp',
      image3: '/beethar.webp',
      image4: '/beetrootpickle.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 1.8,
    },
    {
      id: 15,
      name: 'Parsnips',
      scientific_name: 'Pastinaca sativa',
      description: 'Sweet root crop; flavor improves after frost.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.5,
      storage: 'Cool, dark, ventilated; 3–4 months',
      image: '/parsnip-plant.webp',
      image2: '/soil3.webp',
      image3: '/parsniphar.webp',
      image4: '/parnsipsto.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 1.8,
    },
    {
      id: 16,
      name: 'Kumara',
      scientific_name: 'Ipomoea batatas',
      description: 'Sweet potato; needs warm soil and curing before storage.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 100,
      days_to_harvest_max: 140,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cure 7–10 days, store at 12–15°C',
      image: '/kumera.webp',
      image2: '/soil3.webp',
      image3: '/kumera2.webp',
      image4: '/kumarasto.webp',
      consumption_adult_kg: 12,
      consumption_child_kg: 6,
    },
    {
      id: 17,
      name: 'Tomatoes',
      scientific_name: 'Solanum lycopersicum',
      description: 'Warm-season fruiting plant; needs support.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 3,
      yield_per_plant_max: 6,
      storage: 'Best fresh; short refrigeration possible',
      image: '/tomato.webp',
      image2: '/tomatoStake.webp',
      image3: '/tomatohar.webp',
      image4: '/tomatosto.webp',
      consumption_adult_kg: 15,
      consumption_child_kg: 9,
    },
    {
      id: 18,
      name: 'Capsicum',
      scientific_name: 'Capsicum annuum',
      description:
        'Warm-season fruiting vegetable grown for its sweet, crisp peppers. Thrives in full sun and benefits from staking as heavy fruit develops.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 2,
      yield_per_plant_max: 4,
      storage:
        'Store at 7–10°C for up to 2 weeks or slice and freeze for later use.',
      image: '/bell-pepper.webp',
      image2: '/capsicumtrellis.webp',
      image3: '/capsicumharvest.webp',
      image4: '/capsicumjar.webp',
      consumption_adult_kg: 5,
      consumption_child_kg: 3,
    },
    {
      id: 19,
      name: 'Cucumbers',
      scientific_name: 'Cucumis sativus',
      description: 'Vining summer crop, best supported on trellis.',
      soil_id: 1,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 3,
      yield_per_plant_max: 8,
      storage: 'Use fresh; refrigerate short term',
      image: '/cucumber.webp',
      image2: '/cucumbergrow.webp',
      image3: '/cucumberhar.webp',
      image4: '/cucumbersto.webp',
      consumption_adult_kg: 3.5,
      consumption_child_kg: 2,
    },
    {
      id: 20,
      name: 'Turnips',
      scientific_name: 'Brassica rapa subsp. rapa',
      description: 'Quick-growing root crop; greens edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Cool, dark, ventilated; 2–3 months',
      image: '/turnip.webp',
      image2: '/soil3.webp',
      image3: '/turniphar.webp',
      image4: '/turnipssto.webp',
      consumption_adult_kg: 3.5,
      consumption_child_kg: 2,
    },
    {
      id: 21,
      name: 'Apples',
      scientific_name: 'Malus domestica',
      description:
        'Apple trees are hardy deciduous fruit trees that thrive in cool to temperate climates. They prefer full sun, well-drained fertile soil, and regular pruning to encourage strong growth and good fruiting.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 50,
      yield_per_plant_max: 200,
      storage:
        'Store apples in a cool, dark, well-ventilated place. Many varieties keep for months when refrigerated.',
      image: '/apple.webp',
      image2: '/appletree.webp',
      image3: '/applehar.webp',
      image4: '/applesto.webp',
      consumption_adult_kg: 26,
      consumption_child_kg: 18,
    },
    {
      id: 22,
      name: 'Avocado',
      scientific_name: 'Persea americana',
      description:
        'Avocado trees thrive in warm, frost-free regions with excellent drainage. They require full sun, protection from wind, and consistent moisture while young. Once established, they are hardy and productive evergreen fruit trees.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 40,
      yield_per_plant_max: 150,
      storage:
        'Store avocados at room temperature until ripe. Once softened, refrigerate to extend shelf life for several days.',
      image: '/avocado.webp',
      image2: '/avostake.webp',
      image3: '/avohar.webp',
      image4: '/avosto.webp',
      consumption_adult_kg: 3.5,
      consumption_child_kg: 2.5,
    },
    {
      id: 23,
      name: 'Basil',
      scientific_name: 'Ocimum basilicum',
      description:
        'Basil is a tender annual herb that thrives in warm weather and rich, fertile soil. It requires full sun, consistent moisture, and regular harvesting to encourage bushy growth. Perfect for summer gardens in New Zealand.',
      soil_id: 4,
      spacing_id: 2,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage:
        'Store fresh basil stems in a glass of water at room temperature. Do not refrigerate as cold temperatures damage the leaves.',
      image: '/basil.webp',
      image2: '/soil4.webp',
      image3: '/basilhar.webp',
      image4: '/basilsto.webp',
      consumption_adult_kg: 0.3,
      consumption_child_kg: 0.18,
    },
    {
      id: 24,
      name: 'Blueberry',
      scientific_name: 'Vaccinium corymbosum',
      description:
        'Blueberries thrive in acidic, well-drained soil and full sun. They require consistent moisture and benefit from mulching with pine needles or bark to maintain acidity.',
      soil_id: 5,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 1,
      days_to_harvest_min: 540,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 1,
      yield_per_plant_max: 4,
      storage:
        'Refrigerate berries for up to one week or freeze for long-term storage.',
      image: '/blueberry.webp',
      image2: '/soil5.webp',
      image3: '/blueberryhar.webp',
      image4: '/blueberrysto.webp',
      consumption_adult_kg: 1.2,
      consumption_child_kg: 0.84,
    },
    {
      id: 25,
      name: 'Chives',
      scientific_name: 'Allium schoenoprasum',
      description:
        'Chives are hardy perennial herbs that grow well in most NZ climates. They prefer full sun and rich soil with steady moisture.',
      soil_id: 4,
      spacing_id: 7,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage:
        'Refrigerate in an airtight bag or freeze chopped chives for later use.',
      image: '/chives1.webp',
      image2: '/soil4.webp',
      image3: '/chivesharvest.webp',
      image4: '/chivessto.webp',
      consumption_adult_kg: 0.25,
      consumption_child_kg: 0.15,
    },
    {
      id: 26,
      name: 'Coriander',
      scientific_name: 'Coriandrum sativum',
      description:
        'Coriander prefers cooler weather and grows well in spring and autumn in New Zealand. It bolts quickly in summer heat.',
      soil_id: 4,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 40,
      days_to_harvest_max: 55,
      yield_per_plant_min: 0.03,
      yield_per_plant_max: 0.1,
      storage:
        'Refrigerate stems in a jar of water; use promptly as leaves deteriorate quickly.',
      image: '/coriander.webp',
      image2: '/soil4.webp',
      image3: '/corianderhar.webp',
      image4: '/coriandersto.webp',
      consumption_adult_kg: 0.35,
      consumption_child_kg: 0.21,
    },
    {
      id: 27,
      name: 'Mint',
      scientific_name: 'Mentha spicata',
      description:
        'Mint is a vigorous, fast-spreading herb ideal for pots. It prefers rich, moist soil and part sun in NZ conditions.',
      soil_id: 4,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage:
        'Keep stems in water at room temperature or refrigerate loosely wrapped.',
      image: '/mint.webp',
      image2: '/soil4.webp',
      image3: '/minthar.webp',
      image4: '/mintsto.webp',
      consumption_adult_kg: 0.4,
      consumption_child_kg: 0.24,
    },
    {
      id: 28,
      name: 'Parsley',
      scientific_name: 'Petroselinum crispum',
      description:
        'Parsley grows well year-round in many parts of NZ. It prefers rich soil and steady watering.',
      soil_id: 4,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage:
        'Refrigerate wrapped in a damp paper towel or stand stems in water.',
      image: '/parsley.webp',
      image2: '/soil4.webp',
      image3: '/parsleyhar.webp',
      image4: '/parsleysto.webp',
      consumption_adult_kg: 0.5,
      consumption_child_kg: 0.3,
    },
    {
      id: 29,
      name: 'Sage',
      scientific_name: 'Salvia officinalis',
      description:
        'Sage thrives in warm, dry NZ summers and prefers full sun and well-drained soil.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 75,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage: 'Air-dry or refrigerate wrapped loosely.',
      image: '/sage.webp',
      image2: '/soil2.webp',
      image3: '/sagehar.webp',
      image4: '/sagebutter.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.12,
    },
    {
      id: 30,
      name: 'Strawberry',
      scientific_name: 'Fragaria × ananassa',
      description:
        'Strawberries thrive in sunny NZ gardens with rich, well-drained soil. Mulching helps suppress weeds and keep fruit clean.',
      soil_id: 4,
      spacing_id: 13,
      requirements_id: 5,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 1,
      storage: 'Refrigerate unwashed strawberries and use within a few days.',
      image: '/strawberry.webp',
      image2: '/soil4.webp',
      image3: '/strawberryhar.webp',
      image4: '/strawberrysto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.4,
    },
    {
      id: 31,
      name: 'Watermelon',
      scientific_name: 'Citrullus lanatus',
      description:
        'Watermelons need hot summers, full sun, and well-drained soil. Best grown in warmer parts of New Zealand.',
      soil_id: 2,
      spacing_id: 14,
      requirements_id: 5,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 80,
      days_to_harvest_max: 100,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Store whole melons at room temperature; refrigerate once cut.',
      image: '/watermelon.webp',
      image2: '/soil2.webp',
      image3: '/watermelonhar.webp',
      image4: '/watermelonsto.webp',
      consumption_adult_kg: 6,
      consumption_child_kg: 4.2,
    },
    {
      id: 32,
      name: 'Feijoa',
      scientific_name: 'Acca sellowiana',
      description:
        'Feijoas are hardy NZ favourites that tolerate wind and cooler climates, producing fragrant fruit in autumn.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 10,
      yield_per_plant_max: 30,
      storage: 'Store feijoas in the fridge for up to a week or freeze pulp.',
      image: '/feijoa.webp',
      image2: '/feijoastake.webp',
      image3: '/feijoahar.webp',
      image4: '/feijoasto.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 2.1,
    },
    {
      id: 33,
      name: 'Garlic',
      scientific_name: 'Allium sativum',
      description:
        'Garlic grows well in NZ when planted in winter and harvested in mid-summer. It prefers free-draining soil and full sun.',
      soil_id: 2,
      spacing_id: 10,
      requirements_id: 2,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 210,
      days_to_harvest_max: 240,
      yield_per_plant_min: 0.04,
      yield_per_plant_max: 0.08,
      storage: 'Dry bulbs thoroughly and store in a cool, dark place.',
      image: '/garlic.webp',
      image2: '/soil2.webp',
      image3: '/garlichar.webp',
      image4: '/garlicsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.6,
    },
    {
      id: 34,
      name: 'Lemon',
      scientific_name: 'Citrus limon',
      description:
        'Lemons thrive in warm NZ climates, especially the North Island. They need full sun, good drainage, and protection from frost.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage:
        'Store lemons at room temperature for 1 week or refrigerate for longer.',
      image: '/lemon.webp',
      image2: '/lemontelis.webp',
      image3: '/lemonhar.webp',
      image4: '/lemonsto.webp',
      consumption_adult_kg: 3.2,
      consumption_child_kg: 2.24,
    },
    {
      id: 35,
      name: 'Orange',
      scientific_name: 'Citrus sinensis',
      description:
        'Oranges grow best in frost-free NZ regions with plenty of sun. They require moist, fertile, well-drained soil.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 80,
      storage: 'Store oranges in the fridge to extend freshness.',
      image: '/orange.webp',
      image2: '/soil1.webp',
      image3: '/orangeharv.webp',
      image4: '/orangesto.webp',
      consumption_adult_kg: 6,
      consumption_child_kg: 4.2,
    },
    {
      id: 36,
      name: 'Peaches',
      scientific_name: 'Prunus persica',
      description:
        'Peaches grow well in many NZ regions, especially where summers are warm and dry. They require full sun and yearly pruning.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage:
        'Store ripe peaches in the fridge for several days or freeze slices.',
      image: '/peaches.webp',
      image2: '/soil1.webp',
      image3: '/peachhar.webp',
      image4: '/peachsto.webp',
      consumption_adult_kg: 2.5,
      consumption_child_kg: 1.75,
    },
    {
      id: 37,
      name: 'Butternut Squash',
      scientific_name: 'Cucurbita moschata',
      description:
        'A vigorous vine producing sweet, tan-skinned squash with excellent storage qualities. Thrives in warm, sunny conditions.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 100,
      days_to_harvest_max: 120,
      yield_per_plant_min: 3,
      yield_per_plant_max: 6,
      storage:
        'Cure for 7–10 days before storing in a cool, dry place for up to 6 months.',
      image: '/squash.webp',
      image2: '/soil3.webp',
      image3: '/squash1.webp',
      image4: '/squash2.webp',
      consumption_adult_kg: 5,
      consumption_child_kg: 3,
    },
    {
      id: 38,
      name: 'Courgette (Zucchini)',
      scientific_name: 'Cucurbita pepo',
      description:
        'Fast-growing summer squash that produces abundant fruit over many weeks. Harvest regularly for best production.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 60,
      yield_per_plant_min: 4,
      yield_per_plant_max: 10,
      storage:
        'Refrigerate for up to one week or grate and freeze for later use.',
      image: '/zuchini.webp',
      image2: '/soil3.webp',
      image3: '/zuchini1.webp',
      image4: '/zuchini2.webp',
      consumption_adult_kg: 6,
      consumption_child_kg: 3.5,
    },
    {
      id: 39,
      name: 'Snow Peas',
      scientific_name: 'Pisum sativum var. saccharatum',
      description:
        'Flat edible pods harvested while young and tender. Best grown during cooler seasons with support.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 55,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate for up to one week or blanch and freeze.',
      image: '/snowpea.webp',
      image2: '/peatrelis.webp',
      image3: '/snowpea1.webp',
      image4: '/snowpea.webp',
      consumption_adult_kg: 1.5,
      consumption_child_kg: 0.9,
    },
    {
      id: 40,
      name: 'Sugar Snap Peas',
      scientific_name: 'Pisum sativum var. macrocarpon',
      description:
        'Sweet, crisp edible pods that are eaten whole. Performs best in cool weather with a climbing support.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 60,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.7,
      storage:
        'Store in the refrigerator for up to one week or freeze after blanching.',
      image: '/snappea.webp',
      image2: '/peatrelis.webp',
      image3: '/snappea1.webp',
      image4: '/snappea2.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 41,
      name: 'Runner Beans',
      scientific_name: 'Phaseolus coccineus',
      description:
        'A vigorous climbing bean producing long, tender pods over an extended summer harvest. Requires a strong trellis.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 90,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Best eaten fresh or sliced and frozen after blanching.',
      image: '/runnerbean1.webp',
      image2: '/greenbean-trellis.webp',
      image3: '/runnerbean1.webp',
      image4: '/runnerbean3.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 42,
      name: 'Broad Beans',
      scientific_name: 'Vicia faba',
      description:
        'Hardy cool-season bean producing large pods filled with nutritious beans. Excellent winter and early spring crop.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1,
      storage:
        'Refrigerate for several days or shell and freeze for long-term storage.',
      image: '/broadbean.webp',
      image2: '/soil2.webp',
      image3: '/broadbean1.webp',
      image4: '/broadbean2.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 43,
      name: 'Chilli Pepper',
      scientific_name: 'Capsicum annuum',
      description:
        'Warm-season plant producing spicy fruit in a range of heat levels. Thrives in full sun with regular feeding.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 80,
      days_to_harvest_max: 110,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 2,
      storage: 'Dry, freeze, pickle or refrigerate fresh chillies.',
      image: '/chillipepper.webp',
      image2: '/soil1.webp',
      image3: '/chillihar.webp',
      image4: '/chillisto.webp',
      consumption_adult_kg: 0.6,
      consumption_child_kg: 0.1,
    },
    {
      id: 44,
      name: 'Raspberry',
      scientific_name: 'Rubus idaeus',
      description:
        'Hardy cane fruit producing sweet berries during summer. Prefers full sun, fertile soil and annual pruning.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 4,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Refrigerate for several days or freeze immediately.',
      image: '/raspberry.webp',
      image2: '/soil4.webp',
      image3: '/raspberryhar.webp',
      image4: '/raspberrysto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.7,
    },
    {
      id: 45,
      name: 'Blackberry',
      scientific_name: 'Rubus fruticosus',
      description:
        'Vigorous berry-producing cane plant that benefits from training on a trellis. Produces abundant fruit in late summer.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 4,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 2,
      yield_per_plant_max: 5,
      storage: 'Refrigerate for several days or freeze.',
      image: '/blackberry.webp',
      image2: '/soil4.webp',
      image3: '/blackberryhar.webp',
      image4: '/blackberrysto.webp',
      consumption_adult_kg: 0.8,
      consumption_child_kg: 0.5,
    },
    {
      id: 46,
      name: 'Boysenberry',
      scientific_name: 'Rubus ursinus × Rubus idaeus',
      description:
        'Large juicy berry grown on trailing canes. Produces heavy crops in warm New Zealand summers.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 4,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 2,
      yield_per_plant_max: 5,
      storage: 'Refrigerate for several days or freeze for long-term storage.',
      image: '/boysenberry.webp',
      image2: '/soil4.webp',
      image3: '/boysenberry.webp',
      image4: '/boysenberry1.webp',
      consumption_adult_kg: 0.8,
      consumption_child_kg: 0.5,
    },
    {
      id: 47,
      name: 'Pear',
      scientific_name: 'Pyrus communis',
      description:
        'Deciduous fruit tree producing sweet, juicy pears. Thrives in temperate New Zealand climates with full sun.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 30,
      yield_per_plant_max: 100,
      storage: 'Store in a cool place or refrigerate for several months.',
      image: '/pear.webp',
      image2: '/peartree.webp',
      image3: '/pearhar.webp',
      image4: '/pearsto.webp',
      consumption_adult_kg: 4,
      consumption_child_kg: 2.8,
    },
    {
      id: 48,
      name: 'Plum',
      scientific_name: 'Prunus domestica',
      description:
        'Deciduous fruit tree producing sweet, juicy fruit in summer. Prefers full sun, fertile soil and regular pruning.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage:
        'Store ripe plums in the refrigerator for up to one week or freeze for later use.',
      image: '/plum.webp',
      image2: '/plumtree.webp',
      image3: '/plumhar.webp',
      image4: '/plumsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.4,
    },
    {
      id: 49,
      name: 'Nectarine',
      scientific_name: 'Prunus persica var. nucipersica',
      description:
        'Smooth-skinned stone fruit closely related to peaches. Requires full sun and annual pruning for healthy crops.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage: 'Store ripe nectarines in the refrigerator for several days.',
      image: '/nectarine.webp',
      image2: '/nectarinetree.webp',
      image3: '/nectarinehar.webp',
      image4: '/nectarinesto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.4,
    },
    {
      id: 50,
      name: 'Mandarin',
      scientific_name: 'Citrus reticulata',
      description:
        'Small, easy-to-peel citrus fruit that thrives in warm, sheltered New Zealand gardens.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 30,
      yield_per_plant_max: 100,
      storage:
        'Store at room temperature for one week or refrigerate for several weeks.',
      image: '/mandarin.webp',
      image2: '/mandarintree.webp',
      image3: '/mandarinhar.webp',
      image4: '/mandarinsto.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 2,
    },
    {
      id: 51,
      name: 'Lime',
      scientific_name: 'Citrus × aurantiifolia',
      description:
        'Evergreen citrus tree producing tart green fruit. Requires warmth, full sun and protection from frost.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage: 'Store fresh limes in the refrigerator for several weeks.',
      image: '/lime.webp',
      image2: '/limetree.webp',
      image3: '/limehar.webp',
      image4: '/limesto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.6,
    },
    {
      id: 52,
      name: 'Passionfruit',
      scientific_name: 'Passiflora edulis',
      description:
        'Fast-growing climbing vine producing fragrant flowers and sweet tropical fruit. Requires a strong trellis and a sunny position.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 15,
      yield_per_plant_max: 40,
      storage:
        'Store ripe fruit at room temperature or refrigerate for up to two weeks.',
      image: '/passionfruit.webp',
      image2: '/passionfruittrellis.webp',
      image3: '/passionfruithar.webp',
      image4: '/passionfruitsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.4,
    },
    {
      id: 53,
      name: 'Thyme',
      scientific_name: 'Thymus vulgaris',
      description:
        'Hardy perennial herb with aromatic leaves. Prefers full sun and free-draining soil and tolerates dry conditions once established.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 75,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage:
        'Use fresh, refrigerate for a week, or dry for long-term storage.',
      image: '/thyme.webp',
      image2: '/soil2.webp',
      image3: '/thymehar.webp',
      image4: '/thymesto.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.12,
    },
    {
      id: 54,
      name: 'Rosemary',
      scientific_name: 'Salvia rosmarinus',
      description:
        'Evergreen Mediterranean herb that thrives in full sun and well-drained soil. Excellent for low-maintenance gardens.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage: 'Use fresh or dry sprigs for long-term storage.',
      image: '/rosemary.webp',
      image2: '/soil2.webp',
      image3: '/rosemaryhar.webp',
      image4: '/rosemarysto.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.12,
    },
    {
      id: 55,
      name: 'Oregano',
      scientific_name: 'Origanum vulgare',
      description:
        'Perennial culinary herb producing fragrant leaves throughout the growing season. Prefers full sun and well-drained soil.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage: 'Use fresh or dry leaves for later use.',
      image: '/oregano.webp',
      image2: '/soil2.webp',
      image3: '/oregano.webp',
      image4: '/oreganosto.webp',
      consumption_adult_kg: 0.15,
      consumption_child_kg: 0.09,
    },
    {
      id: 56,
      name: 'Dill',
      scientific_name: 'Anethum graveolens',
      description:
        'Fast-growing annual herb with feathery foliage. Ideal for pickling, seafood dishes and attracting beneficial insects.',
      soil_id: 4,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 60,
      yield_per_plant_min: 0.03,
      yield_per_plant_max: 0.1,
      storage: 'Use fresh, refrigerate for several days or freeze chopped.',
      image: '/dill.webp',
      image2: '/soil4.webp',
      image3: '/dillhar.webp',
      image4: '/dillsto.webp',
      consumption_adult_kg: 0.15,
      consumption_child_kg: 0.09,
    },
    {
      id: 57,
      name: 'Eggplant',
      scientific_name: 'Solanum melongena',
      description:
        'Warm-season vegetable producing glossy purple fruit. Thrives in full sun and benefits from staking as fruit develops.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 90,
      yield_per_plant_min: 2,
      yield_per_plant_max: 6,
      storage:
        'Store at 10–12°C for up to one week. Avoid refrigeration below 10°C.',
      image: '/eggplant.webp',
      image2: '/eggplantstake.webp',
      image3: '/eggplanthar.webp',
      image4: '/eggplantsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 58,
      name: 'Celery',
      scientific_name: 'Apium graveolens',
      description:
        'Cool-season vegetable grown for its crisp stalks. Requires consistently moist, fertile soil for the best harvest.',
      soil_id: 1,
      spacing_id: 2,
      requirements_id: 4,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1.5,
      storage: 'Refrigerate for up to two weeks or chop and freeze.',
      image: '/celery.webp',
      image2: '/celerygrow.webp',
      image3: '/celeryhar.webp',
      image4: '/celerysto.webp',
      consumption_adult_kg: 4,
      consumption_child_kg: 2.5,
    },
    {
      id: 59,
      name: 'Spring Onion',
      scientific_name: 'Allium fistulosum',
      description:
        'Quick-growing onion harvested while young. Excellent for succession planting throughout the year.',
      soil_id: 2,
      spacing_id: 1,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.1,
      storage: 'Refrigerate for up to one week or chop and freeze.',
      image: '/springonion.webp',
      image2: '/soil2.webp',
      image3: '/springonionhar.webp',
      image4: '/springonionsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.6,
    },
    {
      id: 60,
      name: 'Radish',
      scientific_name: 'Raphanus sativus',
      description:
        'Fast-growing root vegetable ideal for beginner gardeners. Harvest while roots are young and crisp.',
      soil_id: 2,
      spacing_id: 1,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 25,
      days_to_harvest_max: 40,
      yield_per_plant_min: 0.03,
      yield_per_plant_max: 0.08,
      storage: 'Remove tops and refrigerate roots for up to two weeks.',
      image: '/radish.webp',
      image2: '/soil2.webp',
      image3: '/radishhar.webp',
      image4: '/radishsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.6,
    },
    {
      id: 61,
      name: 'Brussels Sprouts',
      scientific_name: 'Brassica oleracea var. gemmifera',
      description:
        'Cool-season brassica producing many small sprouts along a tall stem. Best flavour develops after cool weather.',
      soil_id: 2,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1.5,
      storage: 'Refrigerate for up to one week or blanch and freeze.',
      image: '/brusselssprouts.webp',
      image2: '/brusselsgrow.webp',
      image3: '/brusselshar.webp',
      image4: '/brusselssto.webp',
      consumption_adult_kg: 1.5,
      consumption_child_kg: 0.9,
    },
    {
      id: 62,
      name: 'Sweetcorn',
      scientific_name: 'Zea mays convar. saccharata',
      description:
        'Warm-season crop producing sweet cobs. Grow in blocks rather than single rows to improve pollination.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 75,
      days_to_harvest_max: 100,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage:
        'Eat as soon as possible after harvest or refrigerate for several days. Freeze kernels after blanching.',
      image: '/sweetcorn.webp',
      image2: '/sweetcorngrow.webp',
      image3: '/sweetcorn.webp',
      image4: '/sweetcornsto.webp',
      consumption_adult_kg: 5,
      consumption_child_kg: 3,
    },
    {
      id: 63,
      name: 'Fennel',
      scientific_name: 'Foeniculum vulgare',
      description:
        'Aromatic vegetable grown for its crisp bulb and feathery foliage. Bulbs have a mild aniseed flavour.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 80,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate bulbs for up to one week.',
      image: '/fennel.webp',
      image2: '/fennelgrow.webp',
      image3: '/fennelhar.webp',
      image4: '/fennelsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.6,
    },
    {
      id: 64,
      name: 'Bay Laurel',
      scientific_name: 'Laurus nobilis',
      description:
        'Evergreen tree grown for its aromatic leaves, commonly used to flavour soups, stews and sauces. Prefers a sunny, sheltered position.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 1,
      storage:
        'Dry leaves in a cool, well-ventilated place and store in an airtight container.',
      image: '/baylaurel.webp',
      image2: '/baylaurelgrow.webp',
      image3: '/baylaurelhar.webp',
      image4: '/baylaurelsto.webp',
      consumption_adult_kg: 0.05,
      consumption_child_kg: 0.02,
    },
    {
      id: 65,
      name: 'Thai Basil',
      scientific_name: 'Ocimum basilicum var. thyrsiflora',
      description:
        'A fragrant basil with an anise flavour, commonly used in Southeast Asian cooking. Harvest regularly to encourage bushy growth.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Use fresh or freeze chopped leaves.',
      image: '/thaibasil.webp',
      image2: '/soil2.webp',
      image3: '/thaibasilhar.webp',
      image4: '/thaibasilsto.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.1,
    },
    {
      id: 66,
      name: 'Lavender',
      scientific_name: 'Lavandula angustifolia',
      description:
        'Fragrant perennial herb that attracts bees and other pollinators. Flowers can be used in baking, teas and crafts.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage: 'Dry flower stems and store in an airtight container.',
      image: '/lavender.webp',
      image2: '/lavendergrow.webp',
      image3: '/lavenderhar.webp',
      image4: '/lavendersto.webp',
      consumption_adult_kg: 0.05,
      consumption_child_kg: 0.02,
    },
    {
      id: 67,
      name: 'Chamomile',
      scientific_name: 'Matricaria chamomilla',
      description:
        'Easy-to-grow flowering herb harvested for its daisy-like flowers, commonly dried for herbal tea.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 80,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage: 'Dry flower heads thoroughly before storing.',
      image: '/chamomile.webp',
      image2: '/chamomilegrow.webp',
      image3: '/chamomilehar.webp',
      image4: '/chamomilesto.webp',
      consumption_adult_kg: 0.05,
      consumption_child_kg: 0.02,
    },
    {
      id: 68,
      name: 'Nasturtium',
      scientific_name: 'Tropaeolum majus',
      description:
        'Easy-growing annual with colourful edible flowers and peppery leaves. Excellent companion plant that attracts pollinators and acts as a trap crop for aphids.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 60,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Best eaten fresh. Refrigerate flowers for up to two days.',
      image: '/nasturtium.webp',
      image2: '/soil2.webp',
      image3: '/nasturtiumhar.webp',
      image4: '/nasturtiumhar.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.1,
    },
    {
      id: 69,
      name: 'Calendula',
      scientific_name: 'Calendula officinalis',
      description:
        'Bright annual flower with edible petals. Attracts beneficial insects and is often grown as a companion plant.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 55,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage: 'Dry petals for teas, baking or natural colouring.',
      image: '/calendula.webp',
      image2: '/calendulagrow.webp',
      image3: '/calendulahar.webp',
      image4: '/calendulasto.webp',
      consumption_adult_kg: 0.05,
      consumption_child_kg: 0.02,
    },
    {
      id: 70,
      name: 'Borage',
      scientific_name: 'Borago officinalis',
      description:
        'Fast-growing herb with striking blue edible flowers. Excellent for attracting bees and improving pollination throughout the garden.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 55,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Flowers are best used fresh or frozen into ice cubes.',
      image: '/borage.webp',
      image2: '/boragegrow.webp',
      image3: '/boragehar.webp',
      image4: '/boragesto.webp',
      consumption_adult_kg: 0.1,
      consumption_child_kg: 0.05,
    },
    {
      id: 71,
      name: 'Viola',
      scientific_name: 'Viola × wittrockiana',
      description:
        'Cool-season flowering plant with colourful edible blooms. Popular for garnishing desserts, salads and drinks while attracting pollinators.',
      soil_id: 2,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 80,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage: 'Use flowers fresh or crystallise them for decorating cakes.',
      image: '/viola.webp',
      image2: '/violagrow.webp',
      image3: '/violahar.webp',
      image4: '/violasto.webp',
      consumption_adult_kg: 0.05,
      consumption_child_kg: 0.02,
    },
    {
      id: 72,
      name: 'Cranberry',
      scientific_name: 'Vaccinium macrocarpon',
      description:
        'Low-growing perennial producing tart red berries. Prefers acidic soil and consistent moisture.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 1,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 2,
      storage: 'Refrigerate for several weeks or freeze for long-term storage.',
      image: '/cranberry.webp',
      image2: '/cranberrygrow.webp',
      image3: '/cranberryhar.webp',
      image4: '/cranberrysto.webp',
      consumption_adult_kg: 0.5,
      consumption_child_kg: 0.3,
    },
    {
      id: 73,
      name: 'Fig',
      scientific_name: 'Ficus carica',
      description:
        'Deciduous tree producing sweet, soft fruit in late summer. Thrives in warm, sunny locations.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage: 'Eat fresh within a few days or preserve by drying.',
      image: '/fig.webp',
      image2: '/figtree.webp',
      image3: '/fighar.webp',
      image4: '/figsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 74,
      name: 'Olive',
      scientific_name: 'Olea europaea',
      description:
        'Evergreen tree producing olives for curing or pressing into oil. Requires warm, sunny conditions.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 10,
      yield_per_plant_max: 50,
      storage: 'Fresh olives require curing before eating.',
      image: '/olive.webp',
      image2: '/olivetree.webp',
      image3: '/olivehar.webp',
      image4: '/olivesto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1,
    },
    {
      id: 75,
      name: 'Persimmon',
      scientific_name: 'Diospyros kaki',
      description:
        'Small deciduous tree producing sweet orange fruit in autumn. Best grown in full sun.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 80,
      storage: 'Store at room temperature until ripe, then refrigerate.',
      image: '/persimmon.webp',
      image2: '/persimmontree.webp',
      image3: '/persimmonhar.webp',
      image4: '/persimmonsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 76,
      name: 'Apricot',
      scientific_name: 'Prunus armeniaca',
      description:
        'Early-fruiting stone fruit tree producing sweet orange fruit. Prefers warm, sheltered sites.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage: 'Store ripe fruit in the refrigerator for up to one week.',
      image: '/apricot.webp',
      image2: '/apricottree.webp',
      image3: '/apricothar.webp',
      image4: '/apricotsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 77,
      name: 'Grapes',
      scientific_name: 'Vitis vinifera',
      description:
        'Climbing vine producing bunches of sweet grapes. Requires a sunny site and strong support.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 5,
      yield_per_plant_max: 20,
      storage: 'Refrigerate fresh grapes or dry them to make raisins.',
      image: '/grapes.webp',
      image2: '/grapevine.webp',
      image3: '/grapehar.webp',
      image4: '/grapesto.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 2,
    },
    {
      id: 78,
      name: 'Kiwifruit',
      scientific_name: 'Actinidia deliciosa',
      description:
        'Vigorous climbing vine producing fuzzy brown fruit. Requires male and female plants for pollination unless self-fertile.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 20,
      yield_per_plant_max: 50,
      storage:
        'Store in a cool place until ripe or refrigerate for several weeks.',
      image: '/kiwifruit.webp',
      image2: '/soil1.webp',
      image3: '/kiwifruithar.webp',
      image4: '/kiwifruitsto.webp',
      consumption_adult_kg: 4,
      consumption_child_kg: 2.5,
    },
    {
      id: 79,
      name: 'Hazelnut',
      scientific_name: 'Corylus avellana',
      description:
        'Deciduous tree producing nutritious nuts in late summer and autumn. Requires cross-pollination for best yields.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 5,
      yield_per_plant_max: 15,
      storage: 'Dry thoroughly before storing in a cool, dry place.',
      image: '/hazelnut.webp',
      image2: '/hazelnuttree.webp',
      image3: '/hazelnuthar.webp',
      image4: '/hazelnutsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.5,
    },
    {
      id: 80,
      name: 'Walnut',
      scientific_name: 'Juglans regia',
      description:
        'Large deciduous tree producing nutritious walnuts. Best suited to larger gardens with plenty of space.',
      soil_id: 1,
      spacing_id: 7,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1825,
      days_to_harvest_max: 2555,
      yield_per_plant_min: 20,
      yield_per_plant_max: 80,
      storage:
        'Dry nuts thoroughly before storing in a cool, dry place for several months.',
      image: '/walnut.webp',
      image2: '/soil1.webp',
      image3: '/walnuthar.webp',
      image4: '/walnutsto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1,
    },
    {
      id: 81,
      name: 'Almond',
      scientific_name: 'Prunus dulcis',
      description:
        'Small deciduous tree producing edible almonds. Prefers warm, sunny climates and well-drained soil.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 5,
      yield_per_plant_max: 20,
      storage:
        'Dry harvested almonds thoroughly before storing in an airtight container.',
      image: '/almond.webp',
      image2: '/almondtree.webp',
      image3: '/almondhar.webp',
      image4: '/almondsto.webp',
      consumption_adult_kg: 1,
      consumption_child_kg: 0.5,
    },
    {
      id: 82,
      name: 'Kawakawa',
      scientific_name: 'Piper excelsum',
      description:
        'New Zealand native shrub valued for its aromatic leaves and berries. Leaves are traditionally used in teas and cooking.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 1,
      storage: 'Use fresh leaves or dry them for tea.',
      image: '/kawakawa.webp',
      image2: '/soil4.webp',
      image3: '/kawakawa.webp',
      image4: '/kawakawa.webp',
      consumption_adult_kg: 0.2,
      consumption_child_kg: 0.1,
    },
    {
      id: 83,
      name: 'Horopito',
      scientific_name: 'Pseudowintera colorata',
      description:
        'New Zealand native shrub with peppery leaves used as a natural seasoning. Thrives in sheltered, partially shaded positions.',
      soil_id: 4,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 365,
      days_to_harvest_max: 730,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.8,
      storage: 'Dry leaves before storing in an airtight container.',
      image: '/horopito.webp',
      image2: '/soil4.webp',
      image3: '/horopito.webp',
      image4: '/horopito.webp',
      consumption_adult_kg: 0.1,
      consumption_child_kg: 0.05,
    },
    {
      id: 84,
      name: 'New Zealand Spinach',
      scientific_name: 'Tetragonia tetragonioides',
      description:
        'Fast-growing leafy green native to New Zealand and Australia. Produces spinach-like leaves throughout summer.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Refrigerate for up to one week or blanch and freeze.',
      image: '/nzspinach.webp',
      image2: '/soil2.webp',
      image3: '/nzspinach.webp',
      image4: '/nzspinach.webp',
      consumption_adult_kg: 3,
      consumption_child_kg: 2,
    },
    {
      id: 85,
      name: 'Pūhā',
      scientific_name: 'Sonchus oleraceus',
      description:
        'Traditional leafy green enjoyed in New Zealand. Young leaves are harvested for cooking and have a mild, slightly bitter flavour.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 40,
      days_to_harvest_max: 60,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 2,
      storage: 'Use fresh or refrigerate for several days.',
      image: '/puha.webp',
      image2: '/soil2.webp',
      image3: '/puha.webp',
      image4: '/puha.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
    {
      id: 86,
      name: 'Tamarillo',
      scientific_name: 'Solanum betaceum',
      description:
        'Small tree producing colourful, tangy fruit in autumn. Grows well in frost-free areas of New Zealand.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 2,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 10,
      yield_per_plant_max: 30,
      storage: 'Store ripe fruit in the refrigerator for up to two weeks.',
      image: '/tamarillo.webp',
      image2: '/soil1.webp',
      image3: '/tamarillo.webp',
      image4: '/tamarillosto.webp',
      consumption_adult_kg: 2,
      consumption_child_kg: 1.2,
    },
  ])
}
