/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('recipe_ingredients').del()
  await knex('recipe_ingredients').insert([
    {
      id: 1,
      recipe_id: '1',
      quantity: '1',
      unit: 'kilogram',
      ingredient: 'Baby Potatoes (Any potato will do, really)',
      preparation: 'washed and cut into even sizes',
      display_order: '1',
    },
    {
      id: 2,
      recipe_id: '1',
      quantity: '3',
      unit: 'large',
      ingredient: 'Eggs',
      preparation: '',
      display_order: '2',
    },
    {
      id: 3,
      recipe_id: '1',
      quantity: '150',
      unit: 'grams',
      ingredient: 'Mayonnaise',
      preparation: '',
      display_order: '3',
    },
    {
      id: 4,
      recipe_id: '1',
      quantity: '100',
      unit: 'grams',
      ingredient: 'Sour Cream or Greek Yoghurt',
      preparation: '',
      display_order: '4',
    },
    {
      id: 5,
      recipe_id: '1',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Dijon Mustard',
      preparation: '',
      display_order: '5',
    },
    {
      id: 6,
      recipe_id: '1',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Lemon Juice or Apple Cider Vinegar',
      preparation: '',
      display_order: '6',
    },
    {
      id: 7,
      recipe_id: '1',
      quantity: '2',
      unit: '',
      ingredient: 'Spring Onions',
      preparation: 'finely sliced',
      display_order: '7',
    },
    {
      id: 8,
      recipe_id: '1',
      quantity: '1',
      unit: '',
      ingredient: 'Celery Stalk',
      preparation: 'finely diced',
      display_order: '8',
    },
    {
      id: 8,
      recipe_id: '1',
      quantity: '30',
      unit: 'grams',
      ingredient: 'Gherkins',
      preparation: 'finely chopped',
      display_order: '8',
    },
    {
      id: 9,
      recipe_id: '1',
      quantity: '2',
      unit: 'tablespoons',
      ingredient: 'fresh Parsley or Dill',
      preparation: 'chopped',
      display_order: '9',
    },
    {
      id: 10,
      recipe_id: '1',
      quantity: '½',
      unit: 'teaspoon',
      ingredient: 'Salt',
      preparation: 'plus extra for cooking potatoes',
      display_order: '10',
    },
    {
      id: 11,
      recipe_id: '1',
      quantity: 'To taste',
      unit: '',
      ingredient: 'Black Pepper',
      preparation: 'ground or cracked',
      display_order: '11',
    },
    {
      id: 12,
      recipe_id: '1',
      quantity: '1',
      unit: 'teaspoon',
      ingredient: 'Paprika (sweet or smoked)',
      preparation: 'for garnishing',
      display_order: '12',
    },
     {
      id: 13,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 14,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 15,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 16,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 17,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 18,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 19,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
     {
      id: 20,
      recipe_id: '2',
      quantity: '',
      unit: '',
      ingredient: '',
      preparation: '',
      display_order: '',
    },
    //  {
    //   id: ,
    //   recipe_id: '2',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
  ])
}
