export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('recipe_ingredients').del()
  await knex('recipe_ingredients').insert([
    {
      id: 1,
      recipe_id: '1',
      quantity: '1',
      unit: 'kilogram',
      ingredient: 'Baby Potatoes (Any potato will do, really)',
      preparation: 'washed and cut into even sizes',
      display_order: '1',
    },
    {
      id: 2,
      recipe_id: '1',
      quantity: '3',
      unit: 'large',
      ingredient: 'Eggs',
      preparation: '',
      display_order: '2',
    },
    {
      id: 3,
      recipe_id: '1',
      quantity: '150',
      unit: 'grams',
      ingredient: 'Mayonnaise',
      preparation: '',
      display_order: '3',
    },
    {
      id: 4,
      recipe_id: '1',
      quantity: '100',
      unit: 'grams',
      ingredient: 'Sour Cream or Greek Yoghurt',
      preparation: '',
      display_order: '4',
    },
    {
      id: 5,
      recipe_id: '1',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Dijon Mustard',
      preparation: '',
      display_order: '5',
    },
    {
      id: 6,
      recipe_id: '1',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Lemon Juice or Apple Cider Vinegar',
      preparation: '',
      display_order: '6',
    },
    {
      id: 7,
      recipe_id: '1',
      quantity: '2',
      unit: '',
      ingredient: 'Spring Onions',
      preparation: 'finely sliced',
      display_order: '7',
    },
    {
      id: 8,
      recipe_id: '1',
      quantity: '1',
      unit: '',
      ingredient: 'Celery Stalk',
      preparation: 'finely diced',
      display_order: '8',
    },
    {
      id: 9,
      recipe_id: '1',
      quantity: '30',
      unit: 'grams',
      ingredient: 'Gherkins',
      preparation: 'finely chopped',
      display_order: '8',
    },
    {
      id: 10,
      recipe_id: '1',
      quantity: '2',
      unit: 'tablespoons',
      ingredient: 'fresh Parsley or Dill',
      preparation: 'chopped',
      display_order: '9',
    },
    {
      id: 11,
      recipe_id: '1',
      quantity: '½',
      unit: 'teaspoon',
      ingredient: 'Salt',
      preparation: 'plus extra for cooking potatoes',
      display_order: '10',
    },
    {
      id: 12,
      recipe_id: '1',
      quantity: 'To taste',
      unit: '',
      ingredient: 'Black Pepper',
      preparation: 'ground or cracked',
      display_order: '11',
    },
    {
      id: 13,
      recipe_id: '1',
      quantity: '1',
      unit: 'teaspoon',
      ingredient: 'Paprika (sweet or smoked)',
      preparation: 'for garnishing',
      display_order: '12',
    },
    {
      id: 14,
      recipe_id: '2',
      quantity: '1',
      unit: 'kilogram',
      ingredient: 'Pumpkin',
      preparation: 'peeled and diced',
      display_order: '1',
    },
    {
      id: 15,
      recipe_id: '2',
      quantity: '1',
      unit: '',
      ingredient: 'Carrot',
      preparation: 'peeled and chopped',
      display_order: '2',
    },
    {
      id: 16,
      recipe_id: '2',
      quantity: '1',
      unit: '',
      ingredient: 'Potato',
      preparation: 'peeled and chopped',
      display_order: '3',
    },
    {
      id: 17,
      recipe_id: '2',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Olive Oil',
      preparation: '',
      display_order: '4',
    },
    {
      id: 18,
      recipe_id: '2',
      quantity: '1',
      unit: 'teaspoon',
      ingredient: 'Salt',
      preparation: '(adjust to taste)',
      display_order: '5',
    },
    {
      id: 19,
      recipe_id: '2',
      quantity: '1',
      unit: 'teaspoon',
      ingredient: 'Seasoning of choice (dired herbs, garlic powder etc)',
      preparation: '(Optional)',
      display_order: '7',
    },
    {
      id: 20,
      recipe_id: '2',
      quantity: '½',
      unit: 'teaspoon',
      ingredient: 'Black Pepper',
      preparation: '',
      display_order: '6',
    },
    {
      id: 21,
      recipe_id: '2',
      quantity: '200',
      unit: 'mililitres',
      ingredient: 'Coconut Cream',
      preparation: '',
      display_order: '8',
    },
    {
      id: 22,
      recipe_id: '2',
      quantity: '3-4',
      unit: 'cups',
      ingredient: 'Water',
      preparation: '',
      display_order: '9',
    },
    {
      id: 23,
      recipe_id: '3',
      quantity: '1',
      unit: 'large head',
      ingredient: 'Broccoli',
      preparation: 'cut into small florets',
      display_order: '1',
    },
    {
      id: 24,
      recipe_id: '3',
      quantity: '6',
      unit: 'rashers',
      ingredient: 'Bacon',
      preparation: '',
      display_order: '2',
    },
    {
      id: 25,
      recipe_id: '3',
      quantity: '½',
      unit: 'cup',
      ingredient: 'Raisins',
      preparation: '',
      display_order: '3',
    },
    {
      id: 26,
      recipe_id: '3',
      quantity: '¼',
      unit: 'cup',
      ingredient: 'Red Onion',
      preparation: 'finely diced',
      display_order: '4',
    },
    {
      id: 27,
      recipe_id: '3',
      quantity: '½',
      unit: 'cup',
      ingredient: 'Mayonnaise',
      preparation: '',
      display_order: '5',
    },
    {
      id: 28,
      recipe_id: '3',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Apple Cider Vinegar (or White Vinegar)',
      preparation: '',
      display_order: '6',
    },
    {
      id: 29,
      recipe_id: '3',
      quantity: '1',
      unit: 'tablespoon',
      ingredient: 'Sugar or Honey',
      preparation: '',
      display_order: '7',
    },
    {
      id: 30,
      recipe_id: '3',
      quantity: 'To taste',
      unit: '',
      ingredient: 'Salt',
      preparation: '',
      display_order: '8',
    },
    {
      id: 31,
      recipe_id: '3',
      quantity: 'To taste',
      unit: '',
      ingredient: 'Pepper',
      preparation: '',
      display_order: '9',
    },
    {
      id: 32,
      recipe_id: '3',
      quantity: '¼',
      unit: 'cup',
      ingredient: 'Sunflower Seeds',
      preparation: 'optional',
      display_order: '10',
    },
    {
      id: 33,
      recipe_id: '3',
      quantity: '¼',
      unit: 'cup',
      ingredient: 'Pumpkin Seeds',
      preparation: 'optional',
      display_order: '11',
    },
    {
      id: 34,
      recipe_id: '3',
      quantity: '½',
      unit: 'cup',
      ingredient: 'Cheddar Cheese',
      preparation: 'grated, optional',
      display_order: '12',
    },
    {
      id: 35,
      recipe_id: '3',
      quantity: '¼',
      unit: 'cup',
      ingredient: 'Almonds',
      preparation: 'toasted, optional',
      display_order: '13',
    },
    //  {
    //   id: ,
    //   recipe_id: '4',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '5',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '6',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '7',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '8',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '9',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
    //  {
    //   id: ,
    //   recipe_id: '10',
    //   quantity: '',
    //   unit: '',
    //   ingredient: '',
    //   preparation: '',
    //   display_order: '',
    // },
  ])
}
