export async function seed(knex) {
  // Vegetables
  await knex('vegetables').where('name', 'Potatoes').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Onions').update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Pumpkin / Squash')
    .update({ category_id: 1 })
  await knex('vegetables').where('name', 'Broccoli').update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Cauliflower')
    .update({ category_id: 1 })
  await knex('vegetables').where('name', 'Cabbage').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Lettuce').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Spinach').update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Silverbeet / Swiss Chard')
    .update({ category_id: 1 })
  await knex('vegetables').where('name', 'Kale').update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Peas (Garden / Snap)')
    .update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Beans (Green / Broad)')
    .update({ category_id: 1 })
  await knex('vegetables').where('name', 'Carrots').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Beetroot').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Parsnips').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Kumara').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Tomatoes').update({ category_id: 1 })
  await knex('vegetables')
    .where('name', 'Capsicum / Bell Peppers')
    .update({ category_id: 1 })
  await knex('vegetables').where('name', 'Cucumbers').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Turnips').update({ category_id: 1 })
  await knex('vegetables').where('name', 'Garlic').update({ category_id: 1 })

  // Herbs
  await knex('vegetables').where('name', 'Basil').update({ category_id: 2 })
  await knex('vegetables').where('name', 'Chives').update({ category_id: 2 })
  await knex('vegetables').where('name', 'Coriander').update({ category_id: 2 })
  await knex('vegetables').where('name', 'Mint').update({ category_id: 2 })
  await knex('vegetables').where('name', 'Parsley').update({ category_id: 2 })
  await knex('vegetables').where('name', 'Sage').update({ category_id: 2 })

  // Fruit
  await knex('vegetables').where('name', 'Blueberry').update({ category_id: 3 })
  await knex('vegetables')
    .where('name', 'Strawberry')
    .update({ category_id: 3 })
  await knex('vegetables')
    .where('name', 'Watermelon')
    .update({ category_id: 3 })

  // Trees
  await knex('vegetables').where('name', 'Apples').update({ category_id: 4 })
  await knex('vegetables').where('name', 'Avocado').update({ category_id: 4 })
  await knex('vegetables').where('name', 'Feijoa').update({ category_id: 4 })
  await knex('vegetables').where('name', 'Lemon').update({ category_id: 4 })
  await knex('vegetables').where('name', 'Orange').update({ category_id: 4 })
  await knex('vegetables').where('name', 'Peaches').update({ category_id: 4 })
}
