export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('season').del()

  await knex('season').insert([
    {
      id: 1,
      vege_id: 1,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 2,
      vege_id: 1,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 3,
      vege_id: 1,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 4,
      vege_id: 1,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 5,
      vege_id: 2,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 6,
      vege_id: 2,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 7,
      vege_id: 2,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct,Nov',
    },
    {
      id: 8,
      vege_id: 2,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 9,
      vege_id: 3,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 10,
      vege_id: 3,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 11,
      vege_id: 3,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 12,
      vege_id: 3,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 13,
      vege_id: 4,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 14,
      vege_id: 4,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 15,
      vege_id: 4,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 16,
      vege_id: 4,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 17,
      vege_id: 5,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 18,
      vege_id: 5,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 19,
      vege_id: 5,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 20,
      vege_id: 5,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 21,
      vege_id: 6,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 22,
      vege_id: 6,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 23,
      vege_id: 6,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 24,
      vege_id: 6,
      hardiness_zone: '8b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 25,
      vege_id: 7,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 26,
      vege_id: 7,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 27,
      vege_id: 7,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 28,
      vege_id: 7,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 29,
      vege_id: 8,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 30,
      vege_id: 8,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 31,
      vege_id: 8,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 32,
      vege_id: 8,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 33,
      vege_id: 9,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 34,
      vege_id: 9,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 35,
      vege_id: 9,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 36,
      vege_id: 9,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 37,
      vege_id: 10,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 38,
      vege_id: 10,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 39,
      vege_id: 10,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 40,
      vege_id: 10,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 41,
      vege_id: 11,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 42,
      vege_id: 11,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 43,
      vege_id: 11,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 44,
      vege_id: 11,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 45,
      vege_id: 12,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 46,
      vege_id: 12,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 47,
      vege_id: 12,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 48,
      vege_id: 12,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 49,
      vege_id: 13,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 50,
      vege_id: 13,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 51,
      vege_id: 13,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 52,
      vege_id: 13,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 53,
      vege_id: 14,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 54,
      vege_id: 14,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 55,
      vege_id: 14,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 56,
      vege_id: 14,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 57,
      vege_id: 15,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 58,
      vege_id: 15,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 59,
      vege_id: 15,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 60,
      vege_id: 15,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 61,
      vege_id: 16,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 62,
      vege_id: 16,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 63,
      vege_id: 16,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 64,
      vege_id: 16,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 65,
      vege_id: 17,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 66,
      vege_id: 17,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 67,
      vege_id: 17,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 68,
      vege_id: 17,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 69,
      vege_id: 18,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 70,
      vege_id: 18,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 71,
      vege_id: 18,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 72,
      vege_id: 18,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 73,
      vege_id: 19,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 74,
      vege_id: 19,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 75,
      vege_id: 19,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 76,
      vege_id: 19,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 77,
      vege_id: 20,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 78,
      vege_id: 20,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 79,
      vege_id: 20,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 80,
      vege_id: 20,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 81,
      vege_id: 21,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 82,
      vege_id: 21,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 83,
      vege_id: 21,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 84,
      vege_id: 21,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 85,
      vege_id: 22,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 86,
      vege_id: 22,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 87,
      vege_id: 22,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 88,
      vege_id: 22,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 89,
      vege_id: 23,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 90,
      vege_id: 23,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 91,
      vege_id: 23,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 92,
      vege_id: 23,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 93,
      vege_id: 24,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 94,
      vege_id: 24,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 95,
      vege_id: 24,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 96,
      vege_id: 24,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 97,
      vege_id: 25,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 98,
      vege_id: 25,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 99,
      vege_id: 25,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 100,
      vege_id: 25,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 101,
      vege_id: 26,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 102,
      vege_id: 26,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 103,
      vege_id: 26,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 104,
      vege_id: 26,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 105,
      vege_id: 27,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 106,
      vege_id: 27,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 107,
      vege_id: 27,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 108,
      vege_id: 27,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 109,
      vege_id: 28,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 110,
      vege_id: 28,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 111,
      vege_id: 28,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 112,
      vege_id: 28,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 113,
      vege_id: 29,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 114,
      vege_id: 29,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 115,
      vege_id: 29,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 116,
      vege_id: 29,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 117,
      vege_id: 30,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 118,
      vege_id: 30,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 119,
      vege_id: 30,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 120,
      vege_id: 30,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 121,
      vege_id: 31,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 122,
      vege_id: 31,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 123,
      vege_id: 31,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 124,
      vege_id: 31,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 125,
      vege_id: 32,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 126,
      vege_id: 32,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 127,
      vege_id: 32,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 128,
      vege_id: 32,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 129,
      vege_id: 33,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 130,
      vege_id: 33,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 131,
      vege_id: 33,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 132,
      vege_id: 33,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 133,
      vege_id: 34,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 134,
      vege_id: 34,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 135,
      vege_id: 34,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 136,
      vege_id: 34,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 137,
      vege_id: 35,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 138,
      vege_id: 35,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 139,
      vege_id: 35,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 140,
      vege_id: 35,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 141,
      vege_id: 36,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 142,
      vege_id: 36,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 143,
      vege_id: 36,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 144,
      vege_id: 36,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 145,
      vege_id: 37,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 146,
      vege_id: 37,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 147,
      vege_id: 37,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 148,
      vege_id: 37,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 149,
      vege_id: 38,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 150,
      vege_id: 38,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 151,
      vege_id: 38,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 152,
      vege_id: 38,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },

    {
      id: 153,
      vege_id: 39,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 154,
      vege_id: 39,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 155,
      vege_id: 39,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 156,
      vege_id: 39,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },

    {
      id: 157,
      vege_id: 40,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 158,
      vege_id: 40,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 159,
      vege_id: 40,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 160,
      vege_id: 40,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },

    {
      id: 161,
      vege_id: 41,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 162,
      vege_id: 41,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 163,
      vege_id: 41,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 164,
      vege_id: 41,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr',
    },

    {
      id: 165,
      vege_id: 42,
      hardiness_zone: '9a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 166,
      vege_id: 42,
      hardiness_zone: '9b',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 167,
      vege_id: 42,
      hardiness_zone: '10a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 168,
      vege_id: 42,
      hardiness_zone: '8b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 169,
      vege_id: 43,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 170,
      vege_id: 43,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 171,
      vege_id: 43,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr,May',
    },
    {
      id: 172,
      vege_id: 43,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 173,
      vege_id: 44,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 174,
      vege_id: 44,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 175,
      vege_id: 44,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 176,
      vege_id: 44,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },

    {
      id: 177,
      vege_id: 45,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 178,
      vege_id: 45,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 179,
      vege_id: 45,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 180,
      vege_id: 45,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },

    {
      id: 181,
      vege_id: 46,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 182,
      vege_id: 46,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 183,
      vege_id: 46,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 184,
      vege_id: 46,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },

    {
      id: 185,
      vege_id: 47,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 186,
      vege_id: 47,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 187,
      vege_id: 47,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 188,
      vege_id: 47,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Mar,Apr',
    },

    {
      id: 189,
      vege_id: 48,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 190,
      vege_id: 48,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 191,
      vege_id: 48,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 192,
      vege_id: 48,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Feb,Mar',
    },

    {
      id: 193,
      vege_id: 49,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb',
    },
    {
      id: 194,
      vege_id: 49,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb',
    },
    {
      id: 195,
      vege_id: 49,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Dec,Jan',
    },
    {
      id: 196,
      vege_id: 49,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Feb,Mar',
    },

    {
      id: 197,
      vege_id: 50,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'May,Jun,Jul',
    },
    {
      id: 198,
      vege_id: 50,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'May,Jun,Jul',
    },
    {
      id: 199,
      vege_id: 50,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 200,
      vege_id: 50,
      hardiness_zone: '8b',
      planting_month: 'Jul,Aug',
      harvest_month: 'Jun,Jul,Aug',
    },
    {
      id: 201,
      vege_id: 51,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'May,Jun,Jul,Aug',
    },
    {
      id: 202,
      vege_id: 51,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'May,Jun,Jul,Aug',
    },
    {
      id: 203,
      vege_id: 51,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Apr,May,Jun,Jul',
    },
    {
      id: 204,
      vege_id: 51,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov',
      harvest_month: 'Jun,Jul,Aug',
    },

    {
      id: 205,
      vege_id: 52,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 206,
      vege_id: 52,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 207,
      vege_id: 52,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 208,
      vege_id: 52,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 209,
      vege_id: 53,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 210,
      vege_id: 53,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 211,
      vege_id: 53,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 212,
      vege_id: 53,
      hardiness_zone: '8b',
      planting_month: 'Apr,May',
      harvest_month: 'Nov,Dec',
    },

    {
      id: 213,
      vege_id: 54,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 214,
      vege_id: 54,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 215,
      vege_id: 54,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 216,
      vege_id: 54,
      hardiness_zone: '8b',
      planting_month: 'Apr,May',
      harvest_month: 'Nov,Dec',
    },

    {
      id: 217,
      vege_id: 55,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 218,
      vege_id: 55,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 219,
      vege_id: 55,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 220,
      vege_id: 55,
      hardiness_zone: '8b',
      planting_month: 'Apr,May',
      harvest_month: 'Nov,Dec',
    },

    {
      id: 221,
      vege_id: 56,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 222,
      vege_id: 56,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 223,
      vege_id: 56,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 224,
      vege_id: 56,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },

    {
      id: 225,
      vege_id: 57,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 226,
      vege_id: 57,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 227,
      vege_id: 57,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 228,
      vege_id: 57,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 229,
      vege_id: 58,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 230,
      vege_id: 58,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 231,
      vege_id: 58,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 232,
      vege_id: 58,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 233,
      vege_id: 59,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May,Jun',
      harvest_month: 'Jun,Jul,Aug,Sep,Oct',
    },
    {
      id: 234,
      vege_id: 59,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May,Jun',
      harvest_month: 'Jun,Jul,Aug,Sep,Oct',
    },
    {
      id: 235,
      vege_id: 59,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr,May',
      harvest_month: 'May,Jun,Jul,Aug,Sep',
    },
    {
      id: 236,
      vege_id: 59,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },

    {
      id: 237,
      vege_id: 60,
      hardiness_zone: '9a',
      planting_month: 'Feb,Mar,Apr,Sep,Oct',
      harvest_month: 'Apr,May,Jun,Nov,Dec',
    },
    {
      id: 238,
      vege_id: 60,
      hardiness_zone: '9b',
      planting_month: 'Feb,Mar,Apr,Sep,Oct',
      harvest_month: 'Apr,May,Jun,Nov,Dec',
    },
    {
      id: 239,
      vege_id: 60,
      hardiness_zone: '10a',
      planting_month: 'Jan,Feb,Mar,Aug,Sep',
      harvest_month: 'Mar,Apr,May,Oct,Nov',
    },
    {
      id: 240,
      vege_id: 60,
      hardiness_zone: '8b',
      planting_month: 'Mar,Apr,Sep,Oct',
      harvest_month: 'May,Jun,Nov,Dec',
    },

    {
      id: 241,
      vege_id: 61,
      hardiness_zone: '9a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 242,
      vege_id: 61,
      hardiness_zone: '9b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 243,
      vege_id: 61,
      hardiness_zone: '10a',
      planting_month: 'Jan,Feb,Mar',
      harvest_month: 'May,Jun,Jul,Aug',
    },
    {
      id: 244,
      vege_id: 61,
      hardiness_zone: '8b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 245,
      vege_id: 62,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 246,
      vege_id: 62,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 247,
      vege_id: 62,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 248,
      vege_id: 62,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 249,
      vege_id: 63,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 250,
      vege_id: 63,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 251,
      vege_id: 63,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 252,
      vege_id: 63,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },

    {
      id: 253,
      vege_id: 64,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 254,
      vege_id: 64,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 255,
      vege_id: 64,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 256,
      vege_id: 64,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },

    {
      id: 257,
      vege_id: 65,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 258,
      vege_id: 65,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 259,
      vege_id: 65,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 260,
      vege_id: 65,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },

    {
      id: 261,
      vege_id: 66,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 262,
      vege_id: 66,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 263,
      vege_id: 66,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 264,
      vege_id: 66,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 265,
      vege_id: 67,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 266,
      vege_id: 67,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 267,
      vege_id: 67,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 268,
      vege_id: 67,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jan,Feb,Mar',
    },

    {
      id: 269,
      vege_id: 68,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 270,
      vege_id: 68,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 271,
      vege_id: 68,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 272,
      vege_id: 68,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },

    {
      id: 273,
      vege_id: 69,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 274,
      vege_id: 69,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 275,
      vege_id: 69,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 276,
      vege_id: 69,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Dec,Jan,Feb',
    },

    {
      id: 277,
      vege_id: 70,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 278,
      vege_id: 70,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 279,
      vege_id: 70,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 280,
      vege_id: 70,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },

    {
      id: 281,
      vege_id: 71,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 282,
      vege_id: 71,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 283,
      vege_id: 71,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct,Nov',
    },
    {
      id: 284,
      vege_id: 71,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 285,
      vege_id: 72,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 286,
      vege_id: 72,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 287,
      vege_id: 72,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 288,
      vege_id: 72,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 289,
      vege_id: 73,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 290,
      vege_id: 73,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 291,
      vege_id: 73,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 292,
      vege_id: 73,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 293,
      vege_id: 74,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 294,
      vege_id: 74,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 295,
      vege_id: 74,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 296,
      vege_id: 74,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'May,Jun,Jul',
    },

    {
      id: 297,
      vege_id: 75,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 298,
      vege_id: 75,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 299,
      vege_id: 75,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 300,
      vege_id: 75,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 301,
      vege_id: 76,
      hardiness_zone: '9a',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 302,
      vege_id: 76,
      hardiness_zone: '9b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 303,
      vege_id: 76,
      hardiness_zone: '10a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 304,
      vege_id: 76,
      hardiness_zone: '8b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 305,
      vege_id: 77,
      hardiness_zone: '9a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 306,
      vege_id: 77,
      hardiness_zone: '9b',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 307,
      vege_id: 77,
      hardiness_zone: '10a',
      planting_month: 'Jul,Aug,Sep',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 308,
      vege_id: 77,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 309,
      vege_id: 78,
      hardiness_zone: '9a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 310,
      vege_id: 78,
      hardiness_zone: '9b',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 311,
      vege_id: 78,
      hardiness_zone: '10a',
      planting_month: 'Jul,Aug,Sep',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 312,
      vege_id: 78,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 313,
      vege_id: 79,
      hardiness_zone: '9a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 314,
      vege_id: 79,
      hardiness_zone: '9b',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 315,
      vege_id: 79,
      hardiness_zone: '10a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 316,
      vege_id: 79,
      hardiness_zone: '8b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Mar,Apr,May',
    },

    {
      id: 317,
      vege_id: 80,
      hardiness_zone: '9a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 318,
      vege_id: 80,
      hardiness_zone: '9b',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 319,
      vege_id: 80,
      hardiness_zone: '10a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 320,
      vege_id: 80,
      hardiness_zone: '8b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 321,
      vege_id: 81,
      hardiness_zone: '9a',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 322,
      vege_id: 81,
      hardiness_zone: '9b',
      planting_month: 'May,Jun,Jul',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 323,
      vege_id: 81,
      hardiness_zone: '10a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 324,
      vege_id: 81,
      hardiness_zone: '8b',
      planting_month: 'Jun,Jul,Aug',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 325,
      vege_id: 82,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 326,
      vege_id: 82,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 327,
      vege_id: 82,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 328,
      vege_id: 82,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },

    {
      id: 329,
      vege_id: 83,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 330,
      vege_id: 83,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 331,
      vege_id: 83,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 332,
      vege_id: 83,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },

    {
      id: 333,
      vege_id: 84,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr,May',
    },
    {
      id: 334,
      vege_id: 84,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr,May',
    },
    {
      id: 335,
      vege_id: 84,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb,Mar,Apr',
    },
    {
      id: 336,
      vege_id: 84,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },

    {
      id: 337,
      vege_id: 85,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 338,
      vege_id: 85,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 339,
      vege_id: 85,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 340,
      vege_id: 85,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },

    {
      id: 341,
      vege_id: 86,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 342,
      vege_id: 86,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 343,
      vege_id: 86,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 344,
      vege_id: 86,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Apr,May,Jun',
    },

    {
      id: 345,
      vege_id: 87,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 346,
      vege_id: 87,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 347,
      vege_id: 87,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 348,
      vege_id: 87,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
  ])
}
